extends Reference
class_name Artifacts

const NAMES := [
	"Amulet of Resolve",
	"Ancient War Mask",
	"Ankh",
	"Balanced Staff",
	"Broken Compass",
	"Bucket",
	"Chaos Shard",
	"Daedric Shield",
	"Dragon Egg",
	"Ethereal Cloak",
	"Excalibur",
	"Fire Stone",
	"Golden Chalice",
	"Health Potion",
	"Heart Piece",
	"Horned Helm",
	"Iridium Rod",
	"Laser Gun",
	"Lava Eel",
	"Liquid Courage",
	"Map Fragment",
	"Power Bracelet",
	"Ring of Power",
	"Rare Candy",
	"Sandglass",
	"Star in a Bottle",
	"Unstable Salve",
	"Winged Boots",
]

const NOT_FOUND := {
	"Lava Eel": true,
}

const TABLE := {
	"Amulet of Resolve": preload("res://components/reactive/backpack/artifacts/amulet_of_resolve/amulet_of_resolve.tscn"),
	"Ancient War Mask": preload("res://components/reactive/backpack/artifacts/ancient_war_mask/ancient_war_mask.tscn"),
	"Ankh": preload("res://components/reactive/backpack/artifacts/ankh/ankh.tscn"),
	"Balanced Staff": preload("res://components/reactive/backpack/artifacts/balanced_staff/balanced_staff.tscn"),
	"Broken Compass": preload("res://components/reactive/backpack/artifacts/broken_compass/broken_compass.tscn"),
	"Bucket": preload("res://components/reactive/backpack/artifacts/bucket/bucket.tscn"),
	"Chaos Shard": preload("res://components/reactive/backpack/artifacts/chaos_shard/chaos_shard.tscn"),
	"Daedric Shield": preload("res://components/reactive/backpack/artifacts/daedric_shield/daedric_shield.tscn"),
	"Dragon Egg": preload("res://components/reactive/backpack/artifacts/dragon_egg/dragon_egg.tscn"),
	"Ethereal Cloak": preload("res://components/reactive/backpack/artifacts/ethereal_cloak/ethereal_cloak.tscn"),
	"Excalibur": preload("res://components/reactive/backpack/artifacts/excalibur/excalibur.tscn"),
	"Fire Stone": preload("res://components/reactive/backpack/artifacts/fire_stone/fire_stone.tscn"),
	"Golden Chalice": preload("res://components/reactive/backpack/artifacts/golden_chalice/golden_chalice.tscn"),
	"Health Potion": preload("res://components/reactive/backpack/artifacts/health_potion/health_potion.tscn"),
	"Heart Piece": preload("res://components/reactive/backpack/artifacts/heart_piece/heart_piece.tscn"),
	"Horned Helm": preload("res://components/reactive/backpack/artifacts/horned_helm/horned_helm.tscn"),
	"Iridium Rod": preload("res://components/reactive/backpack/artifacts/iridium_rod/iridium_rod.tscn"),
	"Laser Gun": preload("res://components/reactive/backpack/artifacts/laser_gun/laser_gun.tscn"),
	"Lava Eel": preload("res://components/reactive/backpack/artifacts/lava_eel/lava_eel.tscn"),
	"Liquid Courage": preload("res://components/reactive/backpack/artifacts/liquid_courage/liquid_courage.tscn"),
	"Map Fragment": preload("res://components/reactive/backpack/artifacts/map_fragment/map_fragment.tscn"),
	"Power Bracelet": preload("res://components/reactive/backpack/artifacts/power_bracelet/power_bracelet.tscn"),
	"Rare Candy": preload("res://components/reactive/backpack/artifacts/rare_candy/rare_candy.tscn"),
	"Ring of Power": preload("res://components/reactive/backpack/artifacts/ring_of_power/ring_of_power.tscn"),
	"Sandglass": preload("res://components/reactive/backpack/artifacts/sandglass/sandglass.tscn"),
	"Star in a Bottle": preload("res://components/reactive/backpack/artifacts/star_in_a_bottle/star_in_a_bottle.tscn"),
	"Unstable Salve": preload("res://components/reactive/backpack/artifacts/unstable_salve/unstable_salve.tscn"),
	"Winged Boots": preload("res://components/reactive/backpack/artifacts/winged_boots/winged_boots.tscn"),
}
